// <auto-generated />
namespace DemoEF6.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class AddMigrationaddProduct : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddMigrationaddProduct));
        
        string IMigrationMetadata.Id
        {
            get { return "201411241024090_Add-Migration addProduct"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
